### PR TITLE
Updated the Tests Badge URL in README.md

### LINKED ISSUE #3: README.md entry for Tests (beginning of file) is pointing to a wrong URL
Set it to a correct value.

Instead of:
https://github.com/username/project-name/actions/workflows/tests.yml

set it to:
https://github.com/rodested/secman/actions/workflows/tests.yml

### PR DESCRIPTION
**Pull request by AsilbekT**
Changed the Tests URL to the following
https://github.com/rodested/secman/actions/workflows/tests.yml/badge.svg
https://github.com/rodested/secman/actions/workflows/tests.yml

### CODE REVIEW

**Comment by rodested** [comment]
Thanks AsilbekT! Merging it now.

**Comment by rodested** [comment]
Merging after review.

**Comment by rodested** [comment]
closes #3

**Comment by AsilbekT** [comment]
have you added to the tests.yml file the badge?

**Pull request merged**
